### ISSUE TITLE
Asset Store link dead

### ISSUE THREAD

**Issue by OskarZyg** [llamacademy/christmas-lights#1]
The asset store page linked in the README is now dead.
![image](https://user-images.githubusercontent.com/56176746/178141219-c82a7dfb-c5e6-4017-be9b-11c50941a397.png)

**Comment by llamacademy** [comment]
Thanks for letting me know. I updated the readme to keep a link there for anyone who already had that package added to their assets, and included a new link to help you find alternatives.
